{% set name = "okapi-em" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/okapi-em-{{ version }}.tar.gz
  sha256: 0aa724d59d95e03e7e257008c447c8fc5a380f86fbcd792b98bcd1d582ae2e22

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - magicgui
    - qtpy
    - chafer
    - napari
    - opencv
    - quoll >=0.0.4

test:
  imports:
    - okapi_em
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/okapi-em/
  summary: napari plugin to deal with charging artifacts in tomography electron microscopy data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
